export default [
  { value: 'Alternative Music', label: 'Alternative Music' },
  { value: 'Blues', label: 'Blues' },
  { value: 'Classical Music', label: 'Classical Music' },
  { value: 'Country Music', label: 'Country Music' },
  { value: 'Dance Music', label: 'Dance Music' },
  { value: 'Easy Listening', label: 'Easy Listening' },
  { value: 'Electronic Music', label: 'Electronic Music' },
  { value: 'European Music (Folk / Pop)', label: 'European Music (Folk / Pop)' },
  { value: 'Hip Hop / Rap', label: 'Hip Hop / Rap' },
  { value: 'Indie Pop', label: 'Indie Pop' },
  { value: 'Inspirational (incl. Gospel)', label: 'Inspirational (incl. Gospel)' },
  { value: 'Asian Pop (J-Pop, K-pop)', label: 'Asian Pop (J-Pop, K-pop)' },
  { value: 'Jazz', label: 'Jazz' },
  { value: 'Latin Music', label: 'Latin Music' },
  { value: 'New Age', label: 'New Age' },
  { value: 'Opera', label: 'Opera' },
  { value: 'Pop (Popular music)', label: 'Pop (Popular music)' },
  { value: 'R&B / Soul', label: 'R&B / Soul' },
  { value: 'Reggae', label: 'Reggae' },
  { value: 'Rock', label: 'Rock' },
  { value: 'Singer / Songwriter (inc. Folk)', label: 'Singer / Songwriter (inc. Folk)' },
  { value: 'World Music / Beats', label: 'World Music / Beats' },
  { value: '', label: '' },
];